### ISSUE TITLE
Callback not firing on error

### ISSUE THREAD

**Issue by ghost** [convio/luminateExtend#66]
Hi Noah,

I commented a few months back and got no response so I'm re-commenting here. Updated for more recent sample.

I'm using LuminateExtend in a Donation form for the first time, and when things are good, they're very good. But I am having some problems with error handling. Here's the sample:

http://www.centralparknyc.org/calendar/events/belvedere-s-kingdom-4-5-2014-1.html

It's in preview mode, so you can hit it all you like.

Code here:

https://github.com/cpc-comm/cpc-eventix/blob/master/AllToursPage-v8.html

If I make a sample donation with the 4111... credit card number, all is peachy; I've added copious amounts of console.log messages in the callback function, and all are working as expected. However, if I enter a bad CC number, I get nothing. Well, I get an error response from the server, but the callback doesn't fire. To be thorough, I added success AND error functions, but it doesn't look like either is being called. Any thoughts?

Bo

UPDATE: I switched to a generic debugging callback that _should_ just dump the response, but it doesn't fire at all upon receiving a "403 Forbidden" response from the server...

**Comment by seantjohnson-dev** [comment]
I am getting the same error on my end. I don't know why this issue has been closed because there is no answer to this thread and clearly this is still an issue. You can take a look at my case at https://childhelp.magstage.com/donate. I have the preview param set too so you can try to submit and test as much as you'd like. When I type in an invalid credit card, I get a 403 from the Luminate server but no callback is fired. As you can see on the form, I have the callback named 'donateCallback'. You can find this function in 'donate-form.js' in the sources tab of your devtools. How do we get the callback to fire on error? BTW, when all of the information is correct,  the success callback gets fired properly. I just need the error to fire too so I can handle the errors properly.
